language: julia
julia:
  - 0.4
  - nightly
notifications:
  email: false
#script: # the default script does the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("ValueOrientedRiskManagementInsurance")'
